# This workflow builds and checks the package for release
name: Build

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"
    - run: pip install tox

    - name: Test build integrity
      run: tox -e build